server:
  port: 8002
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.cqust.springcloud.entities
  mapper-locations: classpath:mybatis/mapper/**/*.xml


spring:
  application:
    name: microservicecloud-dept
  datasource:
    url: jdbc:mysql:///cloudDB01
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-dept8002
    prefer-ip-address: true
info:
    app.name: cqust-microservicecloud
    company.name: www.cqust.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$
